Prep for release

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,10 +11,17 @@ _check_skip: &check_skip
       circleci-agent step halt;
     fi
 
+# gen3 resource classes are Linux VM only and are valid only with the `current`
+# image tag; medium.gen3 has 2 vCPUs and 8 GiB at 7 credits/min
+executors:
+  linux:
+    machine:
+      image: ubuntu-2604:current
+    resource_class: medium.gen3
+
 jobs:
   docs-build:
-    machine:
-        image: default
+    executor: linux
     steps:
         - checkout
 
@@ -93,37 +100,57 @@ jobs:
               - ~/.cache/pip
 
   docs-deploy:
-    # will only be run on main branch
+    # runs on main (deployed to dev/) and maint/X.Y (deployed to X.Y/)
     docker:
-      - image: cimg/node:lts
+      - image: cimg/python:3.13
     steps:
-      - checkout
-
       - attach_workspace:
-          at: doc/_build
-
-      - run:
-          name: Install and configure dependencies
-          # do not update gh-pages above 3.0.0
-          # see: https://github.com/tschaub/gh-pages/issues/354
-          command: |
-            npm install gh-pages@3.0.0
-            git config --global user.email "circle@mne.com"
-            git config --global user.name "Circle Ci"
+          at: /tmp/build
 
       - add_ssh_keys:
           fingerprints:
             - "13:a4:d4:26:26:fe:ea:a8:1a:f4:0b:0e:33:67:74:7d"
 
       - run:
-          # push built docs into the `dev` directory on the `gh-pages` branch
           name: Deploy docs to gh-pages branch
-          command: node_modules/gh-pages/bin/gh-pages.js --dotfiles --message "doc updates [skip ci]" --dist doc/_build/html --dest ./dev
-
+          command: |
+            set -eo pipefail
+            python -m pip install "docstacks @ git+https://github.com/larsoner/docstacks@7b37f458f9c575cb665821eaa894101ceac487b1"
+            git config --global user.email "circle@mne.com"
+            git config --global user.name "Circle Ci"
+            mkdir -p ~/.ssh
+            ssh-keyscan github.com >> ~/.ssh/known_hosts
+            git clone --branch gh-pages git@github.com:mne-tools/mne-bids.git ~/site
+            cd ~/site
+            if [ "${CIRCLE_BRANCH}" == "main" ]; then
+              DIR=dev
+            else
+              DIR=${CIRCLE_BRANCH#maint/}
+            fi
+            if ! echo "${DIR}" | grep -qE '^([0-9]+\.[0-9]+|dev)$'; then
+              echo "Refusing to deploy: branch ${CIRCLE_BRANCH} maps to invalid directory '${DIR}'."
+              exit 1
+            fi
+            STABLE=$(readlink stable)
+            CMD=deploy
+            EXTRA=()
+            if [ "${DIR}" == "dev" ]; then
+              # label the dev entry with the release after stable, e.g. "0.20 (devel)"
+              EXTRA=(--name "$(echo "${STABLE}" | awk -F. '{print $1"."$2+1}') (devel)")
+            elif [ "$(printf '%s\n%s\n' "${STABLE}" "${DIR}" | sort -V | tail -n1)" != "${STABLE}" ]; then
+              # first deploy of a release newer than stable: repoint stable and the switcher in one commit
+              CMD=promote
+            fi
+            python -m docstacks ${CMD} /tmp/build/html "${DIR}" "${EXTRA[@]}" \
+              --base-url https://mne.tools/mne-bids/ \
+              --source-sha "${CIRCLE_SHA1}" \
+              --message "CircleCI ${CMD} of ${DIR} docs (${CIRCLE_BUILD_NUM}) [skip ci]" \
+              --push
+            # squash history onto the previous squash commit every ~20 deploys
+            python -m docstacks prune --keep 20 --min-squash 20 --push
 
   link-check:
-    machine:
-        image: default
+    executor: linux
     steps:
       - checkout
 
@@ -163,7 +190,9 @@ workflows:
             - docs-build
           filters:
             branches:
-              only: main
+              only:
+                - main
+                - /maint\/.*/
 
   nightly:
     jobs:
